version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for Gradle Main
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for Gradle Android
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
  # Maintain dependencies for Firebase
  - package-ecosystem: "npm"
    directory: "/Cloud Functions/functions"
    schedule:
      interval: "daily"
