version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
plugins:
  fixme:
    enabled: true
  pmd:
    enabled: true
  sonar-java:
    enabled: true
    channel: beta
    config:
      sonar.java.source: 8
    checks:
      squid:S3776:
        enabled: false
ratings:
  paths:
  - "**.java"
exclude_patterns: [
  "References/"
]
