language: bash # Cannot use android for kvm
sudo: true
dist: bionic # Bionic is needed for KVM Nested Virtualization
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/gradle/caches/"
    - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
env:
  global:
    - API_LEVEL=28
    - ANDROID_EMULATOR_API_LEVEL=28 # Try on 28 first for emulator, if it works we can go 29
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=x86_64
    - ANDROID_FLAVOUR=google_apis # Use default for non-google
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_TARGET=android-25
    - ANDROID_TAG=google_apis
    - DISCORD_URL=https://raw.githubusercontent.com/itachi1706/travis-ci-discord-webhook/master/send.sh
    # KVM Self setup of Android SDK
    - ANDROID_HOME=${HOME}/android-sdk # Default location for SDK
    - ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" # From Android Dev Site
    - JDK="1.8" # Android JDK
    - TOOLS=${ANDROID_HOME}/tools # SDK Tools Location
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
    - ESPRESSO=1 # Espresso Instrumentation Tests
    - ESPRESSO=0 # Unit Tests
matrix:
    allow_failures:
        - env: ESPRESSO=1
    fast_finish: true
before_install:
  # Setup Android SDK JDK
  - export TARGET_JDK="${JDK}"
  - JDK="1.8"
  - chmod +x ./travisscript/install-jdk-travis.sh
  - source ./travisscript/install-jdk-travis.sh

  # Setup Android SDK
  - wget -q "${ANDROID_TOOLS_URL}" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - mkdir -p ~/.android
  - echo 'count=0' > ~/.android/repositories.cfg
  - yes | sdkmanager --licenses >/dev/null
  - yes | sdkmanager "platform-tools" >/dev/null
  - yes | sdkmanager "tools" >/dev/null
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
  - yes | sdkmanager "platforms;android-$API_LEVEL" >/dev/null # Current Android compileSDK
install:
  # Download Emulator Files
  - yes | sdkmanager "platforms;android-$ANDROID_EMULATOR_API_LEVEL" >/dev/null # Android Emulator Platform
  - yes | sdkmanager "emulator" >/dev/null
  - yes | sdkmanager "system-images;android-$ANDROID_EMULATOR_API_LEVEL;$ANDROID_FLAVOUR;$ANDROID_ABI" >/dev/null # Android Emulator Image

  # Setup Linux KVM
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
  - sudo adduser $USER libvirt
  - sudo adduser $USER kvm

  # Launch Android Emulator
  - android list targets
  - chmod +x ./travisscript/startemu.sh
  - ./travisscript/startemu.sh

  # Switch back to target JDK
  - JDK="${TARGET_JDK}"
  - source ~/.install-jdk-travis.sh
before_script:
  # Original Steps continued
  #- mkdir "$ANDROID_HOME/licenses" || true
  #- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  #- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  #- yes | sdkmanager "platforms;android-28" # Temporary fix for checksum mismatch (travis-ci/#8874)
  - openssl aes-256-cbc -K $encrypted_2969307dece5_key -iv $encrypted_2969307dece5_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  #- android list targets
  - chmod +x gradlew
  #- chmod +x ./travisscript/startemu.sh
  #- ./travisscript/startemu.sh
  #- ./gradlew clean # Uncomment to clean cache
  - travis_retry ./gradlew assembleDebug
  - travis_retry ./gradlew assembleDebugAndroidTest
script: if [ $ESPRESSO -eq 1 ]; then travis_retry travis_wait ./gradlew connectedAndroidTest -x assembleDebug -x assembleDebugAndroidTest; else travis_retry travis_wait ./gradlew test -x assembleDebug -x assembleDebugAndroidTest; fi
after_success:
  - mv ./app/build/outputs/apk/debug/app-debug.apk ./app/build/outputs/apk/debug/CheesecakeUtilities-debug.apk
  - ls ./app/build/outputs/apk/
  - ls ./app/build/outputs/apk/debug/
  - wget $DISCORD_URL
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - ls $TRAVIS_BUILD_DIR/app/build/outputs/androidTest-results/connected/
  - cat $TRAVIS_BUILD_DIR/app/build/outputs/androidTest-results/connected/TEST-*.xml
  - wget $DISCORD_URL
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  provider: releases
  api_key: "$OAUTH_KEY"
  file: "./app/build/outputs/apk/debug/CheesecakeUtilities-debug.apk"
  skip_cleanup: true
  on:
    tags: true
notifications:
  irc:
    channels:
      - chat.freenode.net#itachi1706mc
      - irc.esper.net#itachi1706
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}"
      - 'Build Status : %{message}'
      - 'Change view : %{compare_url}'
      - 'Build details : %{build_url}'
  email:
    recipients:
      - "$PRIVATE_EMAIL"
    on_success: change
    on_failure: always
  slack:
    secure: kEKJ+tmlXUZSvnD64bk4I3Jt1Rn6TEAvxOpWguJaaBTwbzvXjsf8FWdNlcqA1znBU5nN9HHqFQDwMoKByCUI+6soihghDfC0wKSiC/qUbpG0310P6awR61ToEj6nkBlWB95Vkn+Vl8eOLgG0xTTN1K7vB9UQGJ/oXPpwH7zi/HL1jg9vuv8HYV2XqLnE6tAq3h9RUGnfIS8g+tvhlMvEPGd/S0b9hg7hmzJwatiZ5VWN9ED1nyrgepmgXmNtxRA8XMQ7pczv3wS5bPr7kaS4KIeGkrxymuGyxW/bNcI2EAO7rrjgTTn6olZY0RKpBR62Q3nnZXOBFGdRxcJO0Ei/Xtqe7G6x2Jed5f4n8hP4PBYUxK437gQGNtCFB8u2k/G3t0kHMSbcGHFVG3lTBfQ7OavETXkZdTLkJgwMrvUw8HNaKGvWUeOQM07m7MyObBzNF40NdTm9GKJhL5B/TGDrjkcAtLQs1ZG3UGAdwVNfw6H8e5NlxSlcHb60KAHhA+9qPALBUvyMJA/5TLjNvKpKG9t4licIjvp0i5xVO36vgwH4P+IctvGV8yYKYnIwoviAbtGcYP/nbwsy9+D6oSIbWUUJDDnZQ93ocHTv1IIM3zQrysX8+2dGNhDgr1322F/xeslt1kLPC4tMdflaeG+vxlYP33eVy7C1WIw1qsCHAQU=
